### ISSUE TITLE
HYPE examples use hype methods that don't exist in Hype library ?? 

### ISSUE THREAD

**Issue by kronpano** [tracerstar/processing-360-video#1]
The Hype example2 use 
hype.extended.layout.HSphereLayout; 
which is a layout that doesn't exist in the Hype library.

I have the HYPE library installed in version 2.0.2 but the only extended layouts I can find are Grid, Hex, Polar and Shape

Did you extend the Hype library or am I missing something??

Same applies to example1 where the H.updateBehavior is being used.
This example I can get to work by commenting out H.updateBehavior but it has "stitching errors" whenever a sphere crosses a cubemap boundary - see attached image
![errors](https://user-images.githubusercontent.com/22873114/30910273-f5bd13ea-a37b-11e7-82c1-3231bc68cf05.jpg)

**Comment by tracerstar** [comment]
The main branch of HYPE is somewhat behind the version we are developing, Joshua and I haven't got around to merging the staging branch into the main branch. You need to install HYPE from the "lib_staging" branch to get the latest dev version, and that has the HSphereLayout in there.

https://github.com/hype/HYPE_Processing/tree/lib_staging

You will also not get the stitching errors in your image and you'll also have access to all the newest features we add to HYPE.

**Comment by kronpano** [comment]
Will give it a go - thanks!!

**Comment by kronpano** [comment]
Works perfectly !!!

**Comment by tracerstar** [comment]
Great! Have fun with it.
